name: CI Tests

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:

  basic_checks:
    name: Basic environment and code checks / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          environment-file: environment.yml
      - name: Python info
        run: |
          which python
          python --version
      - name: Show conda info and list
        run: |
          conda info
          conda list
      - name: Show pip list
        run: |
          pip list
